accountapp/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path('create/', AccountCreateView.as_view(), name='create'),
    path('login/', LoginView.as_view(template_name = 'accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

cignography/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from photoapp.views import ImageListView

urlpatterns = [
    # path('', ImageListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('photos/', include('photoapp.urls')),
    path('accounts/', include('accountapp.urls')),
    path('guestbook/', include('guestbook.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main.views import intro, about
from django.conf import settings
from django.conf.urls.static import static

app_name = 'main'

urlpatterns = [
    path('', intro, name='intro'),
    path('about/', about, name='about')
]

accountapp/models.py
from django.db import models

# Create your models here.

# class Texts(models.Model):
#     text = models.CharField(max_length=255, null = False)
#     # 공백허용하지 않음
    

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm

class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args: any, **kwargs: any):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True

accountapp/views.py
from django.shortcuts import render
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse, reverse_lazy

# from accountapp.models import Texts
# Create your views here.

class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('main:intro')
    template_name = 'create.html'

from django.http import HttpResponse, HttpResponseRedirect

from accountapp.forms import AccountUpdateForm
from accountapp.decorators import account_ownership_required
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

has_ownership = [
    account_ownership_required, login_required
]

class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('main:intro')
    # reverse_lazy는 함수와 클래스의 불러오는 방식이 달라짐. 클래스에서 reverse를 사용할 수 없음.
    template_name = 'accountapp/create.html'
    # 어느 html을 쓸지.

class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'

# @method_decorator(has_ownership, 'get')
# @method_decorator(has_ownership, 'post')

class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountUpdateForm
    context_object_name = 'target_user'
    template_name = 'accountapp/update.html'

# @method_decorator(has_ownership, 'get')
# @method_decorator(has_ownership, 'post')

class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('main:intro')
    template_name = 'accountapp/delete.html'

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style=" max-width: 600px; margin: 4rem auto">
        <form action="{% url 'accountapp:create' %}" method = 'post'>
            {% csrf_token %} 
            {% bootstrap_form form %}
            {% comment %} {{ form }} {% endcomment %}

            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>

{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}

{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <h2>Quit</h2>
        <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method = 'post'>
            {% csrf_token %} 

            <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
        </form>
    </div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}
{% block content %}

<div>
    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <p>{{ target_user.date_joined }}</p>

        {% comment %} user은 접속을 한사람 {% endcomment %}
        
        <h2>{{ target_user.username }}</h2>

        {% if target_user == user %}
        
        <a href="{% url 'accountapp:update' pk=user.pk %}">
            <p>Change Info</p>
        </a>
        <a href="{% url 'accountapp:delete' pk=user.pk %}">
            <p>Quit</p>
        </a>

        {% endif %}
    </div>
</div>

{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% comment %} {% load bootstrap4 %} {% endcomment %}
{% block content %}
    
<div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div> 
            <h4>Login</h4>
        </div>
        <div>
            <form action="" method="post">
                {% csrf_token %}
                {% comment %} {% bootstrap_form form %} {% endcomment %}
                {{ form }}
                
                <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
            </form> 
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class = 'mb-4'>
            <h1>Change Info</h1>
        </div>

        <form action="{% url 'accountapp:update' pk=target_user.pk %}" method = 'post'>
            {% csrf_token %} 
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>

{% endblock %}