cignography/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from photoapp.views import ImageListView

urlpatterns = [
    # path('', ImageListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('photos/', include('photoapp.urls')),
    path('accounts/', include('accountapp.urls')),
    path('guestbook/', include('guestbook.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

guestbook/urls.py
from django.urls import path
from guestbook.views import CommentCreateView, CommentListView, CommentDeleteView, Comment
from django.views.generic import TemplateView

app_name = "guestbook"

urlpatterns = [
        path('', CommentListView.as_view(), name='guestbook'),
        path('delete/<int:pk>', CommentDeleteView.as_view(), name='delete'),
        path('create/', CommentCreateView.as_view(), name='create'),
        # path('', TemplateView.as_view(template_name='guestbook/guestbook.html'), name='guestbook'),

]

main/urls.py
from django.urls import path
from main.views import intro, about
from django.conf import settings
from django.conf.urls.static import static

app_name = 'main'

urlpatterns = [
    path('', intro, name='intro'),
    path('about/', about, name='about')
]

photoapp/urls.py
from django.urls import path
from photoapp.views import photo
# from django.conf import settings
# from django.conf.urls.static import static
from django.views.generic import TemplateView
from photoapp.views import ImageCreateView, ImageDetailView, ImageUpdateView, ImageListView, ImageDeleteView

app_name = 'photoapp'

urlpatterns = [
    path('', TemplateView.as_view(template_name = 'photoapp/photos.html' ), name='photo'),
    path('list', ImageListView.as_view(template_name = 'photoapp/list.html'), name = 'list'),
    path('create/', ImageCreateView.as_view(), name = 'create'),
    path('detail/<int:pk>', ImageDetailView.as_view(), name = 'detail'),
    path('update/<int:pk>', ImageUpdateView.as_view(template_name = 'photoapp/update.html'), name = 'update'),
    path('delete/<int:pk>', ImageDeleteView.as_view(template_name = 'photoapp/delete.html'), name = 'delete'),
]

templates/base.html
<html>
    {% include 'head.html' %}
    {% block link %}
    {% endblock link %}

<body>
    {% include 'header.html' %}

    {% block content %}
    {% endblock content %}

    {% include 'footer.html' %}
</body>

</html>

templates/footer.html
<style>
    .footer {
        height: 30px;
        margin:7px;
        display:flex;
        justify-content: center;
        text-align:center;
        align-items:center;
        color: gray;
    }
    
    @media (max-width:767px) {    
        .footer {
            height: 5vh;
            color: lightgray;
            font-size: 2vh;

        }
    }

</style>


<div class='footer'>
    © 2023 CIGNO. ALL RIGHTS RESERVED.
</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit = no">    

    <!-- METADATA OPENGRAPH -->
    
    {% comment %} <meta property="og:url" content="cignography.github.io"> {% endcomment %}
    <meta property="og:title" content="CiGNography">
    <meta property="og:type" content="website">
    <meta property="og:description" content="작품을 감상해보세요">
    <meta property="og:image" content= "{% static 'opengraph.jpg'%} ">
    <link rel="stylesheet" href="{% static "header.css" %}">

    <!-- METADATA -->
    <title>CiGNography</title>
    
    <!-- BOOTSTRAP  -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

</head>

templates/header.html
{% load static %}

<body>
    <nav class="navbar">
        <div class="navbar-logo">
            <a href="{% url 'main:intro' %}">
                <img src="{% static 'logo_white.png' %}" alt="logo" />
            </a>
        </div>
        <div class="navbar-menu">
            {% comment %} <a href="{% url 'main:intro' %}"><span>Intro</span></a>
            <a href="">|</a> {% endcomment %}
            <a href="{% url 'photoapp:list'%}"<span>Photo</span></a>
            <a href="">|</a>
            <a href="{% url 'guestbook:guestbook'%}"<span>GuestBook</span></a>
            <a href="">|</a>
            <a href="{% url 'main:about'%}"<span>About</span></a>
        </div>
    </nav>

    <article></article>
</body>