accountapp/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path('create/', AccountCreateView.as_view(), name='create'),
    path('login/', LoginView.as_view(template_name = 'accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

cignography/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from photoapp.views import ImageListView

urlpatterns = [
    # path('', ImageListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('photos/', include('photoapp.urls')),
    path('accounts/', include('accountapp.urls')),
    path('guestbook/', include('guestbook.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main.views import intro, about
from django.conf import settings
from django.conf.urls.static import static

app_name = 'main'

urlpatterns = [
    path('', intro, name='intro'),
    path('about/', about, name='about')
]

photoapp/urls.py
from django.urls import path
from photoapp.views import photo
# from django.conf import settings
# from django.conf.urls.static import static
from django.views.generic import TemplateView
from photoapp.views import ImageCreateView, ImageDetailView, ImageUpdateView, ImageListView, ImageDeleteView

app_name = 'photoapp'

urlpatterns = [
    path('', TemplateView.as_view(template_name = 'photoapp/photos.html' ), name='photo'),
    path('list', ImageListView.as_view(template_name = 'photoapp/list.html'), name = 'list'),
    path('create/', ImageCreateView.as_view(), name = 'create'),
    path('detail/<int:pk>', ImageDetailView.as_view(), name = 'detail'),
    path('update/<int:pk>', ImageUpdateView.as_view(template_name = 'photoapp/update.html'), name = 'update'),
    path('delete/<int:pk>', ImageDeleteView.as_view(template_name = 'photoapp/delete.html'), name = 'delete'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.

def intro(request):
    return render(request, 'main/main.html')

def about(request):
    return render(request, 'main/about.html')

main/templates/main/about.html
{% extends 'base.html' %} {% load static %}

{% block link %}
    <link rel="stylesheet" href = {% static "about.css" %}>
    <script src="https://unpkg.com/typeit@8.3.3/dist/index.umd.js"></script>
    <script src="https://kit.fontawesome.com/0a0459ea94.js" crossorigin="anonymous"></script>
{% endblock link %}

{% block content %}

<div class="container">
    <div class="about">
        <div class="myImage">
            <img src="{% static "mimo.jpg" %}" alt="profile_image">
        </div>
        <div class="info">
            <div class="name">SUNGHOON KIM</div>
            <div class="links">
                <a href="https://unsplash.com/@cignography" target="_blank">
                    <p><i class="fa-brands fa-unsplash fa-2xl"></i>UNSPLASH</p>
                </a>
                <a href="https://www.instagram.com/cignography/" target="_blank">
                    <p><i class="fa-brands fa-instagram fa-2xl"></i>INSTAGRAM</p>
                </a>
                <a href="mailto:cignography@gmail.com" target="_blank">
                    <p><i class="fa-regular fa-envelope fa-2xl"></i>EMAIL</p>
                </a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

main/templates/main/main.html
{% extends 'base.html' %} {% load static %}

{% block link %}
    <link rel="stylesheet" href = {% static "main.css" %}>
    <script src="https://unpkg.com/typeit@8.3.3/dist/index.umd.js"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
{% endblock link %}

{% block content %}

<script>
    document.addEventListener('DOMContentLoaded', () => {
        let typeitInstance = new TypeIt('#typeit', {
            lifeLike: false,
            speed: 150,
            deleteSpeed: 80,
            startDelay: 500
        })
        
        .type("I'M DEVELOPER")
        .pause(500)
        .delete(9)
        .type("PHOTOGRAPHER")
        .pause(500)
        .delete()
        .type("CIGNOGRAPHY")
        .pause(1000)
        .type(' :')
        

        .go();
    });
</script>

<div class="container">
    <div class="content">
        <div class="intro">
            <h1 id="typeit"></h1>
        </div>
    
        <div class="buttons">
            <a href = {% url 'photoapp:list' %}>
                <div class="btn btn-primary rounded-pill mt-3">
                Photo
                </div>
            </a>
        </div>
    </div>

    <div class="buttons_div"><a href = {% url 'photoapp:list' %}>Photo</a> </div>

    {% if not user.is_authenticated %}
        <div class="buttons_div">
            <a href = "{% url 'accountapp:login' %}?next={{ request.path }}">Sign In</a>
            <a href = "{% url 'accountapp:create' %}">Sign Up</a>
        </div>
        
    {% else %}
        <div class="buttons_div">
            <a href = "{% url 'accountapp:logout' %}?next={{ request.path }}">Logout</a>
            <a href = "{% url 'accountapp:detail' pk=user.pk %}">MyPage</a>
        </div>

    {% endif %}


    <span class="material-symbols-outlined">
        keyboard_double_arrow_down
    </span>
    
</div>



{% endblock %}