cignography/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from photoapp.views import ImageListView

urlpatterns = [
    # path('', ImageListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('photos/', include('photoapp.urls')),
    path('accounts/', include('accountapp.urls')),
    path('guestbook/', include('guestbook.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main.views import intro, about
from django.conf import settings
from django.conf.urls.static import static

app_name = 'main'

urlpatterns = [
    path('', intro, name='intro'),
    path('about/', about, name='about')
]

photoapp/urls.py
from django.urls import path
from photoapp.views import photo
# from django.conf import settings
# from django.conf.urls.static import static
from django.views.generic import TemplateView
from photoapp.views import ImageCreateView, ImageDetailView, ImageUpdateView, ImageListView, ImageDeleteView

app_name = 'photoapp'

urlpatterns = [
    path('', TemplateView.as_view(template_name = 'photoapp/photos.html' ), name='photo'),
    path('list', ImageListView.as_view(template_name = 'photoapp/list.html'), name = 'list'),
    path('create/', ImageCreateView.as_view(), name = 'create'),
    path('detail/<int:pk>', ImageDetailView.as_view(), name = 'detail'),
    path('update/<int:pk>', ImageUpdateView.as_view(template_name = 'photoapp/update.html'), name = 'update'),
    path('delete/<int:pk>', ImageDeleteView.as_view(template_name = 'photoapp/delete.html'), name = 'delete'),
]

photoapp/models.py
from django.contrib.auth.models import User
from django.db import models

class Image(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='image', null=True)
    image = models.ImageField(null=False, upload_to="images/")
    content = models.TextField(null=True)
    created_at = models.DateField(auto_now_add=True, null=True)
    # 생성됐을때 자동으로 날짜 생성

photoapp/forms.py
from django.forms import ModelForm

from photoapp.models import Image

class ImageCreationForm(ModelForm):
    class Meta:
        model = Image
        fields = ['image', 'content']

    def __str__(self) -> str:
        return f'{self.pk}'

photoapp/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, ListView, DeleteView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from photoapp.forms import ImageCreationForm
from photoapp.models import Image
from photoapp.decorators import image_ownership_required, is_superuser

# Create your views here

def photo(request):
    return render(request, 'photoapp/photos.html')

@method_decorator(is_superuser, 'get')
@method_decorator(is_superuser, 'post')

class ImageCreateView(CreateView):
    model = Image
    form_class = ImageCreationForm
    template_name = 'photoapp/create.html'

    def form_valid(self, form):
        # print(self.request.user)
        temp_image = form.save(commit=False)
        temp_image.writer = self.request.user
        temp_image.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('photoapp:detail', kwargs={'pk': self.object.pk})

class ImageDetailView(DetailView):
    model = Image
    context_object_name = 'target_image'
    template_name = 'photoapp/detail.html'

@method_decorator(image_ownership_required, 'get')
@method_decorator(image_ownership_required, 'post')

class ImageUpdateView(UpdateView):
    model = Image
    context_object_name = 'target_image'
    form_class = ImageCreationForm
    template_name = 'photoapp/update.html'

    def get_success_url(self):
        return reverse ('photoapp:detail', kwargs={'pk': self.object.pk})

class ImageListView(ListView):
    model = Image
    ordering = '-id'
    context_object_name = 'photo_list'
    template_name = 'photoapp/list.html'
    paginate_by = 25

@method_decorator(image_ownership_required, 'get')
@method_decorator(image_ownership_required, 'post')

class ImageDeleteView(DeleteView):
    model = Image
    success_url = reverse_lazy('photoapp:list')
    context_object_name = 'target_image'
    template_name = 'photoapp/delete.html'

photoapp/templates/photoapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>Image Create</h4>
        </div>
        
        <form action="{% url 'photoapp:create' %}" method = 'post' enctype='multipart/form-data'>
            {% csrf_token %} 
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>

{% endblock %}

photoapp/templates/photoapp/delete.html
{% extends 'base.html' %}

{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <h2>Delete</h2>
        <form action="{% url 'photoapp:delete' pk=target_image.pk %}" method = 'post'>
            {% csrf_token %} 

            <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
        </form>
    </div>

{% endblock %}

photoapp/templates/photoapp/detail.html
{% extends 'base.html' %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href = {% static "detail.css" %}>
    <script src="https://kit.fontawesome.com/0a0459ea94.js" crossorigin="anonymous"></script>
{% endblock link %}

{% block content %}

<div class='container'>
    <div class='detail'>
        {% comment %} <div class="title">
            <h1>{{target_image.title}}</h1>
        </div> {% endcomment %}

        <div class="images">
            <img src="{{target_image.image.url}}" alt = "">
        </div>
        
        {% comment %} <p> 작성자 : {{target_image.writer}}</p>
        <p> 접속자 : {{request.user}}</p> {% endcomment %}
        
        {% if target_image.content %}

        <div class='content'>
            {{target_image.content}}</h1>
        </div>

        {% endif %}
        
        {% if user.is_superuser %}
        
        <div class="buttons">
            <a class= 'btn btn-dark rounded-pill col-3 mt-2' 
            href="{% url 'photoapp:update' pk=target_image.pk %}">
            <p>Update</p>
        </a>
        <a class= 'btn btn-danger rounded-pill col-3 mt-2' 
        href="{% url 'photoapp:delete' pk=target_image.pk %}">
        <p>Delete</p>
        </a>

    {% endif %}
</div>
    </div>

</div>

{% endblock %}

photoapp/templates/photoapp/list.html
{% extends 'base.html' %} 
{% load static %}

{% block link %}
    <link rel="stylesheet" href = {% static "list.css" %}>
{% endblock link %}

{% block content %}

<html>
    {% if photo_list %}
        <div class="container">
            {% for image in photo_list %}
                <a href="{% url 'photoapp:detail' pk=image.pk %}">
                    {% include 'photoapp/snippets/card.html' with image=image %}
                </a>
            {% endfor %}
        </div>
        
    {% else %}
        <div>
            No Images
        </div>
    
    {% endif %}

    {% include 'photoapp/snippets/pagination.html' with page_obj=page_obj %}
    {% if request.user.is_superuser %}

    <div style='text-align: center;'>
        <a href="{% url 'photoapp:create'%}" class="btn btn-dark rounded-pill col-6 mt-3">
            Create Image
        </a>
    </div>

    {% endif %}

    <script src="{% static 'js/magicgrid.js'%}"></script>

</html>

{% endblock %}

photoapp/templates/photoapp/photos.html
{% extends 'base.html' %} 
{% block content %}
{% load static %}

<html>
    <style>
        .container{
            margin-top: 30px;
        }

        .container div {
            width: 250px;
            {% comment %} height: 500px; {% endcomment %}
            {% comment %} background-color: antiquewhite; {% endcomment %}
            display: flex;
            justify-content: center;
            align-items: center;
            border-radius: 1rem;
            {% comment %} border: 1px solid black; {% endcomment %}
        }

        .container img {
            width: 100%;
        }

    </style>

    <div class="container">

        <div class="photo"><img src="https://cdn.jsdelivr.net/gh/cignography/cignography.github.io@main/photos/1.jpeg" /></div>
        <div class="photo"><img src="https://cdn.jsdelivr.net/gh/cignography/cignography.github.io@main/photos/14.jpeg" /></div>
        <div class="photo"><img src="https://cdn.jsdelivr.net/gh/cignography/cignography.github.io@main/photos/30.jpeg" /></div>
        <div class="photo"><img src="https://cdn.jsdelivr.net/gh/cignography/cignography.github.io@main/photos/91.jpeg" /></div>
        <div class="photo"><img src="https://cdn.jsdelivr.net/gh/cignography/cignography.github.io@main/photos/87.jpeg" /></div>
        <div class="photo"><img src="https://cdn.jsdelivr.net/gh/cignography/cignography.github.io@main/photos/93.jpeg" /></div>
        <div class="photo"><img src="https://cdn.jsdelivr.net/gh/cignography/cignography.github.io@main/photos/54.jpeg" /></div>
        <div class="photo"><img src="https://cdn.jsdelivr.net/gh/cignography/cignography.github.io@main/photos/45.jpeg" /></div>
        <div class="photo"><img src="https://cdn.jsdelivr.net/gh/cignography/cignography.github.io@main/photos/41.jpeg" /></div>
        <div class="photo"><img src="https://cdn.jsdelivr.net/gh/cignography/cignography.github.io@main/photos/21.jpeg" /></div>
        <div class="photo"><img src="https://cdn.jsdelivr.net/gh/cignography/cignography.github.io@main/photos/49.jpeg" /></div>
        <div class="photo"><img src="https://cdn.jsdelivr.net/gh/cignography/cignography.github.io@main/photos/11.jpeg" /></div>
    </div>

    <div style='text-align: center;'>
        <a href="{% url 'photoapp:create'%}" class="btn btn-dark rounded-pill col-6 mt-3">
            Create Image
        </a>
    </div>
    <script src="{% static 'js/magicgrid.js'%}"></script>

</html>

{% endblock %}

photoapp/templates/photoapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>Image Update</h4>
        </div>
        <form action="{% url 'photoapp:create' %}" method = 'post' enctype='multipart/form-data'>
            {% csrf_token %} 
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>

{% endblock %}